// AI music generation via Google Lyria 2 (Vertex AI).
// Supports two auth methods:
//   1. API key (Vertex AI Express Mode) — VERTEX_AI_API_KEY + VERTEX_AI_PROJECT_ID
//   2. Service account JSON — VERTEX_AI_KEY_JSON (or reuses GOOGLE_TTS_KEY_JSON / FIREBASE_ADMIN_KEY_JSON)
// Cost: ~$0.06 per 30-second clip.

import { GoogleAuth } from 'google-auth-library';
import { writeFile, mkdir } from 'fs/promises';
import path from 'path';

const LYRIA_MODEL = 'lyria-002';
const DEFAULT_LOCATION = 'us-central1';

interface AuthResult {
  endpoint: string;
  headers: Record<string, string>;
}

const buildAuth = async (): Promise<AuthResult> => {
  const location = process.env.VERTEX_AI_LOCATION || DEFAULT_LOCATION;

  // Method 1: API key + project ID (Express Mode)
  const apiKey = process.env.VERTEX_AI_API_KEY;
  const projectFromKey = process.env.VERTEX_AI_PROJECT_ID;
  if (apiKey && projectFromKey) {
    const endpoint = `https://${location}-aiplatform.googleapis.com/v1/projects/${projectFromKey}/locations/${location}/publishers/google/models/${LYRIA_MODEL}:predict?key=${apiKey}`;
    return {
      endpoint,
      headers: { 'Content-Type': 'application/json' },
    };
  }

  // Method 2: Service account JSON (OAuth bearer token)
  const json =
    process.env.VERTEX_AI_KEY_JSON ||
    process.env.GOOGLE_TTS_KEY_JSON ||
    process.env.FIREBASE_ADMIN_KEY_JSON;
  if (!json) {
    throw new Error(
      'Vertex AI 인증 미설정: VERTEX_AI_API_KEY+VERTEX_AI_PROJECT_ID 또는 VERTEX_AI_KEY_JSON 필요'
    );
  }

  const credentials = JSON.parse(json);
  const projectId = credentials.project_id;
  if (!projectId) {
    throw new Error('서비스 계정 JSON에 project_id 누락');
  }

  const auth = new GoogleAuth({
    credentials,
    scopes: ['https://www.googleapis.com/auth/cloud-platform'],
  });
  const client = await auth.getClient();
  const tokenResponse = await client.getAccessToken();
  if (!tokenResponse.token) {
    throw new Error('Failed to get access token from service account');
  }

  const endpoint = `https://${location}-aiplatform.googleapis.com/v1/projects/${projectId}/locations/${location}/publishers/google/models/${LYRIA_MODEL}:predict`;
  return {
    endpoint,
    headers: {
      Authorization: `Bearer ${tokenResponse.token}`,
      'Content-Type': 'application/json',
    },
  };
};

export interface GeneratedTrack {
  filePath: string;
  durationSec: number;
  source: 'lyria';
  attribution: string;
}

/**
 * Generate background music with Lyria 2.
 * Each call generates a single 30-second WAV (48kHz).
 */
export const generateLyriaMusic = async (
  prompt: string,
  outDir: string,
  options: { negativePrompt?: string; seed?: number; sampleCount?: number } = {}
): Promise<GeneratedTrack> => {
  const { endpoint, headers } = await buildAuth();

  const body = {
    instances: [
      {
        prompt,
        ...(options.negativePrompt ? { negative_prompt: options.negativePrompt } : {}),
        ...(typeof options.seed === 'number' ? { seed: options.seed } : {}),
      },
    ],
    parameters: {
      sampleCount: options.sampleCount || 1,
    },
  };

  const res = await fetch(endpoint, {
    method: 'POST',
    headers,
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Lyria API failed: HTTP ${res.status}: ${errText.slice(0, 300)}`);
  }

  const data = await res.json();
  const prediction = data?.predictions?.[0];
  if (!prediction?.bytesBase64Encoded && !prediction?.audio) {
    throw new Error(`Lyria response missing audio: ${JSON.stringify(data).slice(0, 200)}`);
  }

  const audioBase64: string = prediction.bytesBase64Encoded || prediction.audio;
  const audioBuffer = Buffer.from(audioBase64, 'base64');

  await mkdir(outDir, { recursive: true });
  const fileName = `lyria-${Date.now()}.wav`;
  const filePath = path.join(outDir, fileName);
  await writeFile(filePath, audioBuffer);

  return {
    filePath,
    durationSec: 30,
    source: 'lyria',
    attribution: `Generated by Google Lyria 2 (prompt: "${prompt.slice(0, 60)}...")`,
  };
};
